#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: provisions the Zoho Books connector (spec §10a). Every value here
# is either public (the client id) or belongs in Vercel's own dashboard, not
# in this repo — the client SECRET is never captured or written by this
# script; see api/zoho-callback.js's header comment for why.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX_HTML="$REPO_DIR/index.html"

banner "Lumine — Zoho Books connector setup"

# ── Stage 1: account + data center ─────────────────────────────────────────
stage "Zoho account & data center"
say "The connector talks to a specific Zoho data center (accounts.zoho.<dc>,"
say "www.zohoapis.<dc>). zoho.js and api/zoho-proxy.js both default to \"in\""
say "(India), matching Lumine's GSTIN-first framing."
if ! confirm "Is your Zoho account on the .in (India) data center?"; then
  warn "After this wizard, update the DC constant in two places to match yours:"
  note "  - zoho.js: const DC = \"in\";"
  note "  - api/zoho-proxy.js: API_BASE = \"https://www.zohoapis.in/books/v3\";"
  pause "Noted — press Enter to continue anyway (the rest of this wizard still applies)."
fi

# ── Stage 2: register the OAuth app ────────────────────────────────────────
stage "Register a Server-based Application"
say "This creates the OAuth app Lumine authenticates against. Server-based"
say "Application is the right type — not Self Client, not Client Credentials —"
say "because api/zoho-callback.js does a real authorization-code exchange."
open_url "https://api-console.zoho.com/"
step "Sign in, then click 'Add Client' → 'Server-based Applications'."
step "Client Name: anything recognizable, e.g. \"Lumine Treasury Demo\"."
step "Homepage URL: your Vercel deployment (next stage covers the exact value)."
pause "Created the client? Press Enter to continue."

# ── Stage 3: redirect URI ──────────────────────────────────────────────────
stage "Set the Authorized Redirect URI"
ask DEPLOY_URL "Your Vercel deployment URL (e.g. https://lumine-opal.vercel.app):"
DEPLOY_URL="${DEPLOY_URL%/}"
REDIRECT_URI="${DEPLOY_URL}/api/zoho-callback"
say "In the client you just created, add this exact Authorized Redirect URI:"
printf '  %s%s%s\n' "$BOLD" "$REDIRECT_URI" "$RESET"
step "Paste it into the 'Authorized Redirect URIs' field and save."
pause "Saved? Press Enter to continue."

# ── Stage 4: client id + secret ────────────────────────────────────────────
stage "Copy the Client ID and Client Secret"
say "Zoho now shows a Client ID and Client Secret."
ask ZOHO_CLIENT_ID "Paste the Client ID (public — safe to commit):"
say "Now copy the Client Secret somewhere safe (a password manager, or just"
say "keep the tab open) — it goes into Vercel's dashboard in Stage 6, never"
say "into a file in this repo, and this wizard will not ask you to paste it"
say "here."
confirm "Have you copied the Client Secret somewhere safe?" || true

# ── Stage 5: write the client id into index.html ───────────────────────────
stage "Write the Client ID into index.html"
if [[ -f "$INDEX_HTML" ]] && grep -q 'window.LUMINE_ZOHO_CLIENT_ID' "$INDEX_HTML"; then
  if confirm "Patch index.html's window.LUMINE_ZOHO_CLIENT_ID automatically?"; then
    sed -i.bak "s#window.LUMINE_ZOHO_CLIENT_ID = \".*\";#window.LUMINE_ZOHO_CLIENT_ID = \"${ZOHO_CLIENT_ID}\";#" "$INDEX_HTML"
    rm -f "${INDEX_HTML}.bak"
    printf '  %s✓ wrote%s the client id into %s\n' "$GREEN" "$RESET" "$INDEX_HTML"
  else
    note "Skipped — paste it in yourself: window.LUMINE_ZOHO_CLIENT_ID = \"${ZOHO_CLIENT_ID}\";"
  fi
else
  warn "Couldn't find the window.LUMINE_ZOHO_CLIENT_ID line in $INDEX_HTML"
  note "Paste it in yourself: window.LUMINE_ZOHO_CLIENT_ID = \"${ZOHO_CLIENT_ID}\";"
  SKIPPED+=("edit index.html's window.LUMINE_ZOHO_CLIENT_ID by hand")
fi

# ── Stage 6: Vercel environment variables ──────────────────────────────────
stage "Add Vercel environment variables"
say "Three env vars, set on the Vercel project (dashboard or CLI) — never in"
say "this repo:"
printf '  %s•%s ZOHO_CLIENT_ID      = %s\n' "$BLUE" "$RESET" "$ZOHO_CLIENT_ID"
printf '  %s•%s ZOHO_CLIENT_SECRET  = %s(the secret from Stage 4)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
printf '  %s•%s ZOHO_REDIRECT_URI   = %s\n' "$BLUE" "$RESET" "$REDIRECT_URI"
open_url "https://vercel.com/dashboard"
step "Open your Lumine project → Settings → Environment Variables."
step "Add all three above (Production, and Preview if you use it)."
note "CLI alternative, run in your own terminal (prompts hide the secret):"
note "  vercel env add ZOHO_CLIENT_ID"
note "  vercel env add ZOHO_CLIENT_SECRET"
note "  vercel env add ZOHO_REDIRECT_URI"
pause "Added all three? Press Enter to continue."

# ── Stage 7: redeploy + Zoho Books data ────────────────────────────────────
stage "Redeploy and check your Zoho Books data"
say "New env vars only take effect on a fresh deployment."
step "Push any commit (this wizard's index.html edit counts), or redeploy"
step "from the Vercel dashboard."
say ""
say "The connector pulls vendors + unpaid bills only. Make sure at least one"
say "Zoho Books organization has a vendor with an unpaid bill — a trial org"
say "works fine."
pause "Ready? Press Enter to continue."

# ── Stage 8: end-to-end check ───────────────────────────────────────────────
stage "Try it"
say "This part can't be done by an AI — signing into a real Zoho account has"
say "to be you."
open_url "${DEPLOY_URL}/"
step "Open the Import tab and click \"Connect Zoho Books\"."
step "Sign in, approve the consent screen, pick your organization if asked,"
step "then click \"Pull vendor ledger\"."
say ""
say "If it works: you'll see a preview table of vendors/bills, ready to Apply."
say "If it doesn't: copy the exact error message shown (or from the browser"
say "console) — that's what turns this from a guess into a fix."
# ──────────────────────────────────────────────────────────────────────────

finish
